[package]
name = "exec_rule"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.8"
itertools = "0.12.1"
proc-macro2 = "1.0.79"
quote = "1.0.35"
regex = "1.10.4"
syn = { version = "2.0.59", features = ["full"] }
